config/routes.rb
Blogger::Application.routes.draw do
  ActiveAdmin.routes(self)
  resources :photos, :only => [:create]

  root to: 'articles#index'
  get "/articles" => redirect("/")
  resources :articles do
    resources :comments
  end
  resources :tags
  resources :authors

  resources :author_sessions, only: [:new, :create, :destroy ]

  get 'about' => 'articles#about'
  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
  get 'signup' => 'authors#new'

  match "/comment_preview" => "comments#preview", :as => "comment_preview", via: [:post]
  match "/edit_preview"  => "articles#preview", :as => "edit_preview", via: [:post]

  get 'archive' => "articles#archive"

end

app/models/article.rb
class Article < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged

	has_many :taggings
	has_many :tags, through: :taggings
	has_many :comments, as: :commentable
	validates :title, presence: true
	validates :body, presence: true
	validates :tag_list, presence: true

  searchable do
    text :title, :body, :stored => true
  end

	def tag_list
		self.tags.collect do |tag|
			tag.name
		end.join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
		new_or_found_tags = tag_names.collect{|name| Tag.find_or_create_by(name: name) }
		self.tags = new_or_found_tags
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper

	before_filter :require_login, only: [:new, :create, :edit, :update, :destroy, :preview]
	before_action :load_article, only: [:show, :destroy, :edit, :update]

	def index
    if params[:search].blank?
    	@articles = Article.paginate(:page => params[:page], :per_page => 5)
    else
    	@articles = Article.solr_search do #conflict with active_admin ransack
    		fulltext params[:search]
    		paginate :page => params[:page], :per_page => 5
    	end.results
    end
		@tags = Tag.all
	end

	def show
		@commentable = @article
		@comments = @commentable.comments
		@comment = Comment.new
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.create(article_params)
		if @article.save
		  redirect_to article_path(@article)
		else
		  render 'new'
		end
	end

	def destroy
		@article.destroy
		redirect_to articles_path
	end

	def edit
	end

	def update
		@article.update(article_params)

		flash.notice = "Article '#{@article.title}' updated"

		redirect_to article_path(@article)
	end

	def preview
		@content = params[:content]
		respond_to do |format|
		  format.js
		end
	end

	def archive
		@articles = Article.all
		@article_months = @articles.group_by { |t| t.created_at.beginning_of_month }
		@paginate_articles = Article.paginate(:page => params[:page], :per_page => 40)
	end

  def about
  end

	private
	  def load_article
	  	@article = Article.friendly.find(params[:id])
	  end

	  def not_authenticated
      flash.alert = "Login require"
	  	redirect_to login_path
	  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

	def article_params
		params.require(:article).permit(:title, :body, :tag_list, :image)
	end

  def tag_class(name)
    #Rails.cache.write('name',["blue","green",""].sample)
    Rails.cache.fetch("#{name}") {["blue","green",""].sample}
  end

end

app/views/articles/_form.html.erb
<div class="article_form">
<%= bootstrap_form_for(article, html: {multipart: true}) do |f| %>

    <p>
    <%= f.text_field :title, label: "标题" %>
    </p>
    <div class="edit_tools">
      <ul class="pills clearfix">
        <div class="left_icons pull-left">
            <li class="edit tabnav-tab selected">
                <a href="#">编辑</a>
            </li>
            <li class="preview tabnav-tab">
                <a href="#">预览</a>
            </li>
        </div>
        <div class="right_icons pull-right">
            <li class="the_insert_code pull-right">
            <div class="dropdown pull-right">
                <a href="#" class="fa fa-code dropdown-toggle" data-placement="top" data-toggle="dropdown" title="插入代码"></a>
                <ul class="dropdown-menu pull-right" role="menu">
                    <li><a class="insert_code" data-content="ruby" id="ruby">Ruby</a>
                    </li>
                    <li><a class="insert_code" data-content="erb" id="erb">HTML / ERB</a>
                    </li>
                    <li><a class="insert_code" data-content="scss" id="scss">CSS / SCSS</a>
                    </li>
                    <li><a class="insert_code" data-content="js" id="js">JavaScript</a>
                    </li>
                    <li><a class="insert_code" data-content="yml" id="yml">YAML </a>
                    </li>
                    <li><a class="insert_code" data-content="coffee" id="coffee">CoffeeScript</a>
                    </li>
                    <li><a class="insert_code" data-content="conf" id="conf">Nginx / Redis  </a>
                    </li>
                    <li><a class="insert_code" data-content="python" id="python">Python</a>
                    </li>
                    <li><a class="insert_code" data-content="php" id="php">PHP</a>
                    </li>
                    <li><a class="insert_code" data-content="java" id="java">Java</a>
                    </li>
                    <li><a class="insert_code" data-content="erlang" id="erlang">Erlang</a>
                    </li>
                    <li><a class="insert_code" data-content="shell" id="shell">Shell / Bash</a>
                    </li>
                </ul>
            </div>
            </li>
            <li class="upload_image pull-right">
                <a href="#" class="fa fa-picture-o image_upload" data-placement="top" data-toggle="tooltip" title="上传图片"></a>
                <input type="file" id="article-upload-images" multiple>
            </li>
        </div>
      </ul>
    </div>
    <p>
    <%= f.text_area :body, label: "正文" %>
    </p>
    <p>
    <%= f.text_field :tag_list %>
    </p>
    <p>
    <%= f.submit "发布文章", data: { disable_with: "提交中...." }, class: "btn btn-success" %>
    </p>
<% end %>
</div>


<%= content_for :template_js do %>
<script>
$(".preview").click(function() {
    $(".edit").removeClass("selected");
    $(this).addClass("selected");
    var b = $(".article_form .form-group").eq(1);
    var preview_content = b.find("textarea").val();
    b.find("textarea").hide();
    b.prepend("<div class='preview-box markdown-format' id='preview-box'>加载中...</div>");
    $.ajax({type: "POST", url: "/edit_preview", data: {content: preview_content} });

    return false;
});

$(".edit").click(function() {
    $(".preview").removeClass("selected");
    $(this).addClass("selected");
    var b = $(".article_form .form-group");
    $(".preview-box").remove();
    b.find('textarea').show();
    return false;
});


Topics = {
    appendImageFromUpload: function(srcs){
        var  txtBox = $("#article_body"),
             caret_pos = txtBox.caret('pos'),
             src_merged = "";
        console.log(srcs);
        srcs.map( function(src) {
          src_merged = "![]("+src+")\n";
        });
        var source = txtBox.val();
        var before_text = source.slice(0, caret_pos);
        txtBox.val(before_text + src_merged + source.slice(caret_pos+1, source.count));
        txtBox.caret('pos',caret_pos + src_merged.length);
        txtBox.focus();
    },


    restoreUploaderStatus: function(){
        $(".upload_image").parent().find("span.loading").remove();
        $(".upload_image").show();
    },


    initUploader: function(){
        $(".image_upload").click( function() {
            $("#article_body").focus();
            $("#article-upload-images").click();
            return false;
        });

        var opts = {
            url : "/photos",
            type : "POST",
            beforeSend : function(){
                $(".upload_image").hide();
                $(".upload_image").before("<span class='loading'>上传中...</span>");
            },
            success : function(result, status, xhr){
                Topics.restoreUploaderStatus();
                Topics.appendImageFromUpload([result]);
            },
            error : function(result, status, errorThrown){
                Topics.restoreUploaderStatus();
                if (result.status === 0) {
                    alert('无法连接.');
                } else if (result.status == 404) {
                    alert('提交的页面不存在');
                } else if (result.status == 500) {
                    alert('内部服务器错误');
                } else if (status === 'parsererror') {
                    alert('提交的json处理失败');
                } else if (status === 'timeout') {
                    alert('超时错误');
                } else if (status === 'abort') {
                    alert('ajax请求中止');
                } else {
                    alert('Uncaught Error.\n' + result.responseText);
                }            
            }
        };

        $("#article-upload-images").fileUpload(opts);
        return false;
    },

    appendCodesFromHint: function(language){
        if(language === null){
            language = '';
        } 
        var  txtBox = $("#article_body");
             caret_pos = txtBox.caret('pos');
             prefix_break = "";
        if(txtBox.val().length > 0){
            prefix_break = "\n";
        }
        var src_merged = "" + prefix_break + "```" + language + "\n\n```\n";
        source = txtBox.val();
        var before_text = source.slice(0, caret_pos);
        txtBox.val(before_text + src_merged + source.slice(caret_pos + 1, source.count));
        txtBox.caret('pos', caret_pos + src_merged.length - 5);
        txtBox.focus();
    },

    insert_code: function(){
        $("a.insert_code").click(function(){
            Topics.appendCodesFromHint($(this).data('content') || $(this).attr('id'));
            return false;
        });
    },
};


Topics.initUploader();
Topics.insert_code();

$('.image_upload').tooltip();
$('.fa-code').tooltip({
    container: 'body'
});
$('.dropdown-toggle').dropdown();

$("textarea#article_body").keydown(function(e) {
  if (e.ctrlKey && e.keyCode == 13) {
    $("input[type=submit]").click();
  }
});
</script>
<% end %>

app/views/articles/_sidebar.html.erb
<div id="sidebar">
<h1>sidebar</h1>
   <ul>
   <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
      created_at <%= article.created_at.strftime("%B") %> month
    </li>
   <% end %>
   </ul>
</div>

app/views/articles/about.html.erb
<% content_for :title, "About Me" %>
<div class="about">
 <h1>About Me</h1>
 <div class="row">
   <div class="col col-md-3 col-sm-3">
     <img class="img-thumbnail img-responsive photo" src="https://avatars0.githubusercontent.com/u/2096566?s=300">
   </div>
   <div class="col col-md-9 col-sm-9">
     <p>这家伙很懒,什么都没有留下</p>
   </div>
 </div>
</div>

<% content_for :template_js do %>
<script>
 if (window.location.pathname == "/about"){
    $(".navbar-left li:nth-child(3)").addClass("active");
  }
</script>
<% end %>

app/views/articles/archive.html.erb
<% content_for :title, "Blogger Archive" %>
<div class="content">
<% @article_months.sort.each do |month, articles| %>
  <h2><%= month.strftime("%Y %B") %></h2>
  <ul class="archive">

  <% for article in articles %>
  <li>
      <%= article.created_at.to_date.to_s(:long) %>
      <a href ="<%= article_path(article) %>"><%= article.title %></a>
  </li>
  <% end %>
  </ul>
<% end %>
</div>


<div class="text-center">
<%= will_paginate @paginate_articles, renderer: BootstrapPagination::Rails %>
</div>

<% content_for :template_js do %>
<script>
  if (window.location.pathname == "/archive"){
    $(".navbar-nav li:nth-child(2)").addClass("active");
  }

</script>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form', :article => @article %>

app/views/articles/index.html.erb
<% content_for :title, "My Blog" %>
<div class="row article-list">
  <div class="col-md-8">
  <% @articles.each do |article| %>
    <article>
      <a href="<%= article_path(article) %>"><h1><%= article.title %></h1></a>

         <i class="fa fa-clock-o"></i>
         <span class="data"><%= article.created_at.strftime("%Y-%m-%d") %></span>
         <div class="comment_count">
           <span class="glyphicon glyphicon-comment"></span>
           <a href="<%= article_path(article) %>"><%= article.comments.count %>条回复</a>
         </div>

      <div class="post_body">
      <p><%= markdown article.body %></p>
      </div>
    </article>
  <% end %>
  </div>
  <div class="col-md-4">
  <div class="panel panel-default">
      <div class="panel-heading">
        <h4>Tags</h4>
      </div>
      <div class="tags-cloud">
      <ul class="list-inline tags">
        <% @tags.each do |tag| %>
         <li class="<%= tag_class(tag.name) %>"><a href="<%= tag_path(tag) %>"><%= tag %><span><%= tag.articles.count %></span></a></li>
        <% end %>
      </ul>
      </div>
    </div>
  </div>
</div>

<div class="text-center">
<%= will_paginate @articles, renderer: BootstrapPagination::Rails %>
</div>

<% content_for :template_js do %>
<script>

  if (window.location.pathname == "/"){
    $(".navbar-left li").first().addClass("active");
  }

</script>
<% end %>


app/views/articles/index.js.erb
<script type="text/javascript" data-turbolinks-eval=false>
$(".article-list").html("<%= escape_javascript(render template: 'articles/index.html.erb') %>")
</script>

app/views/articles/new.html.erb
<% content_for :title, "New Article" %>
<%= render 'form', :article => @article %>

app/views/articles/preview.js.erb
$(".preview-box").html("<%= escape_javascript markdown @content %>");

app/views/articles/show.html.erb
<% content_for :title, @commentable.title %>
<div class="container">
  <div class="blog-post">

	<h1 class="blog-post-title"><a href="<%= article_path(@commentable) %>"><%= @commentable.title %></a></h1>

	<h2 class="label">标签:
	<% @commentable.tags.each do |tag| %>
	    <%= link_to tag.name, tag_path(tag) %>
	<% end %>
	</h2>

    <div class="article-body">
	<p><%= markdown @commentable.body %><p>
	</div>


	<div>

	<%= link_to "<< Back to Articles List", articles_path %>

	<% if logged_in? %>

	<%= link_to "Delete", article_path(@commentable), method: :delete, :confirm => "Really delete the article" %>

	<%= link_to "edit", edit_article_path(@commentable) %>

	<% end %>

	</div>

	</div>

	<div class="comments">

	<h2 class="comment-number">回复(<%= @commentable.comments.count %>)</h2>

	<%= render partial: "comments/comment", locals: { post: @commentable }, collection: @commentable.comments %>

	<div class="bubble">

	<%= render template: "comments/new" %>

	</div>
</div>
<% content_for :template_js do %>
<script>
    $("textarea#comment_body").keydown(function(e) {
      if (e.ctrlKey && e.keyCode == 13) {
        $("input[type=submit]").click();
      }
    });
</script>
<% end %>