config/routes.rb
Blogger::Application.routes.draw do
  ActiveAdmin.routes(self)
  resources :photos, :only => [:create]

  root to: 'articles#index'
  get "/articles" => redirect("/")
  resources :articles do
    resources :comments
  end
  resources :tags
  resources :authors

  resources :author_sessions, only: [:new, :create, :destroy ]

  get 'about' => 'articles#about'
  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
  get 'signup' => 'authors#new'

  match "/comment_preview" => "comments#preview", :as => "comment_preview", via: [:post]
  match "/edit_preview"  => "articles#preview", :as => "edit_preview", via: [:post]

  get 'archive' => "articles#archive"

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings

	def to_s
		name
	end

  def to_param
    "#{name}"
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_filter :require_login, only: [:destroy]

	def show
		@tag = Tag.find_by_name(params[:id])
		@tags = Tag.all
		@test = @tag.articles.paginate(:page => 1, :per_page => 4)
	end

	def index
		@tags = Tag.all
	end

	private
	  def not_authenticated
        redirect_to login_path, :alert => "First log in to view this page."
    end
end

app/views/tags/index.html.erb
<% content_for :title, "All Tags" %>
<h1>All Tags</h1>

<ui>
   <% @tags.each do |tag| %>
   <li>
   <%= link_to tag.name, tag_path(tag) %>
   &nbsp
   </li>
   <% end %>
</ui>

app/views/tags/show.html.erb
<% content_for :title, @tag.name %>
<div class="row article-list">
<div class="primary-content">
  <div class="col-md-8">
  <% @tag.articles.each do |article| %>
    <article>
      <a href="<%= article_path(article) %>"><h1><%= article.title %></h1></a>
         <i class="fa fa-clock-o"></i>
         <span class="data"><%= article.created_at.strftime("%Y-%m-%d")  %></span>
         <span class="comment_count"><%= article.comments.count %>条回复</span>
      <div class="post_body">
      <p><%= article.body %></p>
      </div>
    </article>
  <% end %>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
          <h4>Tags</h4>
        </div>
        <div class="tags-cloud">
        <ul class="list-inline tags">
          <% @tags.each do |tag| %>
           <li class="<%= tag_class(tag.name) %>"><a href="<%= tag_path(tag) %>"><%= tag %><span><%= tag.articles.count %></span></a></li>
          <% end %>
        </ul>
        </div>
      </div>
  </div>
</div>
</div>

<div class="text-center">
<%= will_paginate @test, renderer: BootstrapPagination::Rails %>
</div>