config/routes.rb
Blogger::Application.routes.draw do
  ActiveAdmin.routes(self)
  resources :photos, :only => [:create]

  root to: 'articles#index'
  get "/articles" => redirect("/")
  resources :articles do
    resources :comments
  end
  resources :tags
  resources :authors

  resources :author_sessions, only: [:new, :create, :destroy ]

  get 'about' => 'articles#about'
  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
  get 'signup' => 'authors#new'

  match "/comment_preview" => "comments#preview", :as => "comment_preview", via: [:post]
  match "/edit_preview"  => "articles#preview", :as => "edit_preview", via: [:post]

  get 'archive' => "articles#archive"

end

app/views/layouts/_flash_message.html.erb
<% flash.each do |level, message| %>
  <div class="fade in <%= flash_class(level) %>">
    <a class="close" href="#" data-dismiss="alert"></a>
    <h4 class="alert-heading">Notice!</h4>
    <p><%= message %></p>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <%= form_tag articles_path, :method => :get, :class => "navbar-form navbar-right", :html => {:role => "navigation"}, :remote => true do %>
        <div class="form-group">
         <%= text_field_tag :search, params[:search], :class => "form-control", :placeholder => "Search" %>
        </div>
        <%= submit_tag "Submit", :class => "btn btn-default search-button" %>
      <% end %>
      <% if logged_in? %>
      <ul class="logged-in nav navbar-nav navbar-right">
        <li class="username">
          <a href="#" class="btn btn-inverse dropdown-toggle"  data-toggle="dropdown">
              <%= current_user.username %>
              <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
            <li><a tabindex="-1" href="/articles/new"><i class="fa fa-file"></i> new article</a></li>
            <li class="divider"></li>
            <li><a tabindex="-1" href="/logout"><i class="fa fa-sign-out"></i> Logout</a></li>
          </ul>
        </li>
      </ul>
      <% end %>
      <ul class="nav navbar-nav navbar-left">
        <li>
          <a href="/">首页</a>
        </li>
        <li>
           <a href="/archive">存档</a>
        </li>
        <li>
          <a href="/about">关于</a>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body class="admin-body">
  <%= render 'layouts/flash_message' %>
  <div id ="container">
    <div id="content">
       <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body class="default-body">
  <%= render 'layouts/header' %>
  <%= render 'layouts/flash_message' %>
  <div id ="container">
    <div id="content">
       <%= yield %>
    </div>
  </div>
  <%= yield :template_js %>
</body>
</html>